INSERT INTO DEPARTMENT
VALUES (1, 'Java Department');

INSERT INTO DEPARTMENT
VALUES (2, 'JS Department');


INSERT INTO EMPLOYEE
VALUES (1, 1, 'Test Value 1', 300);
INSERT INTO EMPLOYEE
VALUES (2, 1, 'Test Value 2', 400);
INSERT INTO EMPLOYEE
VALUES (3, 2, 'Test Value 3', 500);
INSERT INTO EMPLOYEE
VALUES (4, 2, 'Test Value 4', 600);